MEADOW_USE_SIMULATOR ?= 0
MEADOW_TESTER_BUILD ?= 0
ifneq ($(MEADOW_TESTER_BUILD),0)
MEADOW_TESTER_BUILD = 1
endif
ifneq ($(MEADOW_USE_SIMULATOR),0)
MEADOW_USE_SIMULATOR = 1
TARGET = simulator:clang::7.0
ARCHS = x86_64
else
MEADOW_USE_SIMULATOR = 0
TARGET = iphone:13.0:8.0
ARCHS = armv7 arm64 arm64e
endif
export CFLAGS TARGET ARCHS MEADOW_USE_SIMULATOR MEADOW_TESTER_BUILD
CFLAGS += -I.. -DMEADOW_TESTER_BUILD=$(MEADOW_TESTER_BUILD) -include macros.h
include $(THEOS)/makefiles/common.mk
SUBPROJECTS += Tweak
ifeq ($(MEADOW_USE_SIMULATOR),0)
SUBPROJECTS += Application
endif
include $(THEOS_MAKE_PATH)/aggregate.mk
