INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = MobileMeadow

MobileMeadow_FILES = $(wildcard *.xm) $(wildcard *.m)
MobileMeadow_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
